---
title: "Plots"
author: "Carlotta Sampels"
date: "2025-03-25"
output: html_document
---
#Setup

```{r Setup, include=FALSE}
knitr::opts_chunk$set(
	echo = TRUE,
	cache = FALSE,
	comment = NA,
	prompt = FALSE)
```

## Clear global environment prior to initiation
```{r Clear global environment}
remove(list = ls())
```

## Read in file with path to ilovedata channel on Teams
```{r Read in paths file}
source(file = "credentials/paths.R")
```

## Load packages
```{r Load packages}
library(ggplot2)
library(dplyr)
library(patchwork)
library(tidyverse)
library(paletteer)
```

## Retrieve the recent date
```{r Recent date}
date = Sys.Date()
date = "2026-03-10"
```

## Read in data

```{r Load data sexual orientation}
dat_sexual_orientation <- read_rds(
  file =
    paste0(filepath_cleaned_data,"dat_after_exclusion_sexual_orientation", date, ".rds")
)
```

```{r Load data gender}
dat_gender <- read_rds(
  file =
    paste0(filepath_cleaned_data,"dat_after_exclusion_gender", date, ".rds")
)
```

# Plots
```{r density plot age}
ggplot(dat_sexual_orientation, aes(x = age, fill = sexual_orientation)) +
  geom_density(alpha = 0.5) +
  labs(title = "Density Plot",
       x = "Age",
       y = "Density",
       fill = "Sexual orientation") +
  theme_minimal() +
  scale_fill_paletteer_d("fishualize::Balistoides_conspicillum") +
  facet_wrap(vars(sexual_orientation),nrow = 6)

ggplot(dat_gender, aes(x = age, fill = gender)) +
  geom_density(alpha = 0.5) +
  labs(title = "Density Plot",
       x = "Age",
       y = "Density",
       fill = "Gender") +
  theme_minimal() +
  facet_wrap(vars(gender),nrow = 4)
```

```{r age sexual orientation}
plot_age_sexual_orientation <- ggplot(dat_sexual_orientation, aes(x = age)) +
  geom_density(fill = "lightblue", alpha = 0.5) +
  geom_vline(xintercept = mean(dat_sexual_orientation$age, na.rm = TRUE), 
             color = "red", linetype = "dashed", size = 1) +  # Mittelwert-Linie
  geom_vline(xintercept = median(dat_sexual_orientation$age, na.rm = TRUE), 
             color = "blue", linetype = "solid", size = 1) + # Median-Linie
  annotate("text", x = mean(dat_sexual_orientation$age, na.rm = TRUE), y = 0, 
           label = paste0("Mean = ", round(mean(dat_sexual_orientation$age, na.rm = TRUE), 2)), 
           color = "black", angle = 90, vjust = 1.5, hjust = 0, size = 6) +
  annotate("text", x = median(dat_sexual_orientation$age, na.rm = TRUE), y = 0, 
           label = paste0("Median = ", round(median(dat_sexual_orientation$age, na.rm = TRUE), 2)),
           color = "black", angle = 90, vjust = -0.5, hjust = 0, size = 6) +
  labs(title = NULL, x = "Age", y = "Density") +
  theme_minimal() +
  theme(
    text = element_text(size = 20),           
    axis.title = element_text(size = 20),   
    #axis.text = element_text(size = 15),     
  )
plot_age_sexual_orientation
```

```{r age gender}
plot_age_gender <- ggplot(dat_gender, aes(x = age)) +
  geom_density(fill = "lightblue", alpha = 0.5) +
  geom_vline(xintercept = mean(dat_gender$age, na.rm = TRUE), 
             color = "red", linetype = "dashed", size = 1) +  # Mittelwert-Linie
  geom_vline(xintercept = median(dat_gender$age, na.rm = TRUE), 
             color = "blue", linetype = "solid", size = 1) + # Median-Linie
  annotate("text", x = mean(dat_gender$age, na.rm = TRUE), y = 0, 
           label = paste0("Mean = ", round(mean(dat_gender$age, na.rm = TRUE), 2)), 
           color = "black", angle = 90, vjust = 1.5, hjust = 0, size = 6) +
  annotate("text", x = median(dat_gender$age, na.rm = TRUE), y = 0, 
           label = paste0("Median = ", round(median(dat_gender$age, na.rm = TRUE), 2)),
           color = "black", angle = 90, vjust = -0.5, hjust = 0, size = 6) +
  labs(title = NULL, x = "Age", y = "Density") +
  theme_minimal() +
  theme(
    text = element_text(size = 20),           
    axis.title = element_text(size = 20),   
    axis.text = element_text(size = 18),     
  )
plot_age_gender
```
#safe

```{r safe plot}
ggsave(
  filename = "plot_age_gender.png",
  plot = plot_age_gender,
  path = "C:/Users/carlo/Documents/work/LGBTQ/plots",
  width = 12, height = 4, units = "in", dpi = 300
)

ggsave(
  filename = "plot_age_sexual_orientation.png",
  plot = plot_age_sexual_orientation,
  path = "C:/Users/carlo/Documents/work/LGBTQ/plots",
  width = 15, height = 5, units = "in", dpi = 300
)
```